In [1]:
import polars as pl

from pathlib import Path

PROJROOT = Path.cwd().parent
RAW_DATA = PROJROOT / "data/raw"
PROCESSED_DATA = PROJROOT / "data/preprocessed"
DATABASES = PROJROOT / "databases"

RESULTS = PROJROOT / "results"

In [17]:
query = (
    pl.scan_csv(RESULTS / "*/grn/adj.tsv", separator='\t')
    .select(['TF', 'target', 'importance'])
    .group_by(['TF', 'target'])
    .agg( pl.col('importance') )
    .with_columns(
        importance=pl.col('importance').list.mean()
    )
)

avg_adj = query.collect()

In [ ]:
avg_adj.sort('importance')

shape: (1_262_197, 3)
┌───────────────┬─────────┬────────────┐
│ TF            ┆ target  ┆ importance │
│ ---           ┆ ---     ┆ ---        │
│ str           ┆ str     ┆ f64        │
╞═══════════════╪═════════╪════════════╡
│ Atf7          ┆ Neo1    ┆ 2.3802e-19 │
│ Zfp780b       ┆ Shcbp1l ┆ 9.1029e-19 │
│ Cebpd         ┆ Reck    ┆ 3.1247e-18 │
│ Nr3c1         ┆ Akap6   ┆ 4.1933e-18 │
│ 3300002I08Rik ┆ Nyap2   ┆ 4.3051e-18 │
│ …             ┆ …       ┆ …          │
│ Stat1         ┆ H2-Q7   ┆ 257.118732 │
│ H2afy         ┆ Psmb8   ┆ 258.329495 │
│ Stat1         ┆ Lgals9  ┆ 283.903475 │
│ Ltf           ┆ S100a9  ┆ 284.477948 │
│ Ltf           ┆ Lyz2    ┆ 311.703703 │
└───────────────┴─────────┴────────────┘

In [20]:
avg_adj.write_csv("adj.tsv", separator='\t')

In [3]:
pl.read_csv(RESULTS / "old-subset/grn/adj.tsv", separator='\t').sort('importance')

shape: (3_524_815, 3)
┌───────────────┬─────────┬────────────┐
│ TF            ┆ target  ┆ importance │
│ ---           ┆ ---     ┆ ---        │
│ str           ┆ str     ┆ f64        │
╞═══════════════╪═════════╪════════════╡
│ Zfp664        ┆ Prg2    ┆ 4.1730e-21 │
│ Ctbp1         ┆ Prg2    ┆ 2.2654e-20 │
│ Yod1          ┆ Gm13822 ┆ 1.2750e-19 │
│ Zhx1          ┆ Gm13822 ┆ 1.4421e-19 │
│ 1810024B03Rik ┆ Prg3    ┆ 1.6186e-19 │
│ …             ┆ …       ┆ …          │
│ Hmgb2         ┆ Birc5   ┆ 116.919452 │
│ Hmgb2         ┆ Tubb5   ┆ 118.938254 │
│ Hmgb2         ┆ Cenpa   ┆ 122.152436 │
│ Rpl6          ┆ Rpl35   ┆ 145.448274 │
│ Hmgb2         ┆ Cks2    ┆ 147.188819 │
└───────────────┴─────────┴────────────┘